- README.md
- deploy.sh
Using `deploy.sh` with the qemux86 target requires changing the port and address for the `ssh` and `scp` commands.  This simplifies that change by extracting those attributes as shell variables.  The function is unchanged from the original.  Fixes #38.
> Simplify changing script for use with qemux86 target.

- analog-asteroid-logo/usr/share/asteroid-launcher/watchfaces/analog-asteroid-logo.qml
- analog-precision/usr/share/asteroid-launcher/watchfaces/analog-precision.qml
- analog-railway/usr/share/asteroid-launcher/watchfaces/analog-railway.qml
- analog-rings/usr/share/asteroid-launcher/watchfaces/analog-rings.qml
- analog-scientific/usr/share/asteroid-launcher/watchfaces/analog-scientific.qml
- analog-tactical/usr/share/asteroid-launcher/watchfaces/analog-tactical.qml
- bold-hour-bebas-v2/usr/share/asteroid-launcher/watchfaces/bold-hour-bebas-v2.qml
- clean-bars/usr/share/asteroid-launcher/watchfaces/clean-bars.qml
- day-clock-24h/usr/share/asteroid-launcher/watchfaces/day-clock-24h.qml
- digital-alternative-default-mosen/usr/share/asteroid-launcher/watchfaces/digital-alternative-default-mosen.qml
- digital-alternative-mosen/usr/share/asteroid-launcher/watchfaces/digital-alternative-mosen.qml
- greenium/usr/share/asteroid-launcher/watchfaces/greenium.qml
- motivational-quotes/usr/share/asteroid-launcher/watchfaces/motivational-quotes.qml
- orbiting-asteroids/usr/share/asteroid-launcher/watchfaces/orbiting-asteroids.qml
- prominent-seconds/usr/share/asteroid-launcher/watchfaces/prominent-seconds.qml
- rainbow-uprising/usr/share/asteroid-launcher/watchfaces/rainbow-uprising.qml
- sporty-round-v2/usr/share/asteroid-launcher/watchfaces/sporty-round-v2.qml
- sporty-round/usr/share/asteroid-launcher/watchfaces/sporty-round.qml
As also proposed for the stock watchfaces https://github.com/AsteroidOS/asteroid-launcher/pull/76/commits/515ca01da43ce7d996058cc9491be0507511c01a 
Solves this issue for all canvas watchfaces https://github.com/AsteroidOS/meta-sparrow-hybris/issues/14
Tested them all on sparrow with `renderStrategy: Canvas.Cooperative` applied to all canvases and the graphic glitch is gone.
https://github.com/AsteroidOS/unofficial-watchfaces/issues/48
> Fix hour hands requestPaint, move to cooperative canvas renderStrategy

- digital-alternative-mosen/usr/share/asteroid-launcher/watchfaces/digital-alternative-mosen.qml
Somehow the live view differed from the screenshot in the watchface list.
Correcting to intended centering.
> Fix vertical centering in digital-alternative-mosen

- analog-goldie/usr/share/asteroid-launcher/watchfaces/analog-goldie.qml
- analog-scientific-v2/usr/share/asteroid-launcher/watchfaces/analog-scientific-v2.qml
- arc/usr/share/asteroid-launcher/watchfaces/Arc.qml
- karlos-matrix/usr/share/asteroid-launcher/watchfaces/karlos-matrix.qml
- kitt/usr/share/asteroid-launcher/watchfaces/kitt.qml
- sporty-round-v2/usr/share/asteroid-launcher/watchfaces/sporty-round-v2.qml
Several of the unofficial watchfaces relied on org.freedesktop.context
for the battery charge level.  We now use Nemo.Mce to get that value, so
this change fixes four of the six affected watchfaces.
> Fix battery display on unofficial watchfaces.

- decimal-time/usr/share/asteroid-launcher/watchfaces/decimal-time.qml
The current watchface was designed for "metric time" defined as 10 hours
per standard day, 100 minutes per hour, and 100 seconds per minute but
there could easily be other values chosen.  This update fully
parameterizes those choices to make it easier to experiment and modify.
> Use named constants to make modification easier

- loader.qml
This adds the option to display the watchface as non-square with a fixed
ratio 85% width to height to match the Oppo watch.
> Add non-square option to tester

- loader.qml
Currently, qmlscene is hardcoded to at least 640x955, not including window decoration. That height doesn't fit well on resolutions under 1080p. For example, I primarily use a laptop with a 1366x768 display, and a 1600x900 monitor above it when docked. You can see here that even on the larger monitor, it cuts across both displays. This is exaggeratedly worse if the majority is on the small display, with the header cut in half across screens.
I decided the best way to get around this would be to move the controls to the side, making the window horizontally shaped. 
On top of this, I have fixed a couple of things:
- Generate previews will always regenerate the transparent image
- Generate previews never assumes status of round option
- Non-square option no longer enabled on startup
Git did a …
> Make qmlscene horizontal + generate preview fixes

- analog-boombox/usr/share/asteroid-launcher/watchfaces/analog-boombox.qml
Shame, shame, shame :P
Initial PR was only tested/developed on watches with 100% charge...
Now installing on a watch with lower charge, it became apparent that i missed to divide by 100. uh uh
> [analog-boombox] Correct battery segments display

- analog-nort/usr/share/asteroid-launcher/watchfaces/analog-nort.qml
Apply the fix found by @beroset were disabling animations in AoD prevents the second hand from being moved to the new position in a lengthy transition after AoD is ended.
> Fix analog nort animations

- analog-weather-glow/usr/share/asteroid-launcher/watchfaces/analog-weather-glow.qml
- Apply the fix found by @beroset  were disabling animations in AoD prevents the second hand from being moved to the new position in a lengthy transition after AoD is ended.
- Remove never hour/minute hand animations to lower performance impact.
> Fix animations being enabled in AoD and nightstand

- loader.qml
This adds the watchface name as the title of the window so it shows something useful instead of "qmlscene."
> Add watchface name as title

- loader.qml
This fixes #83 by persisting the settings.  Note that because we do not set the Qt.application.name and Qt.application.organization the settings are stored under ~/.config/QtProject/QtQmlViewer.conf
> Persist settings

- deploy.sh
I saw that using deploy.sh to add a wallpaper to your device did not allow to have the file be in a different directory than deploy.sh.
This is to fix that.
> Allow giving wallpapers from other paths to deploy.sh

- deploy.sh
The previous commit added quotes around ${source} but the script requires them to be unquoted.  This fixes issue #97 and preserves the ability to push wallpaper from other directories, even if the directory or file name happens to have a space in the name.  That's why the IFS= line is there.
> Fix pushFiles function

- decimal-time/usr/share/asteroid-launcher/watchfaces/decimal-time.qml
This adds a revolutionsPerDay value to make it easier to hack this watchface to do other things.  For a standard 24-hour day and 12-hour watchface, revolutionsPerDay would be set to 2.  In this version, it's set to 1 to be backwards compatible with the existing versions.
> Update decimal-time watchface for easier hacking

- analog-weather-glow/usr/share/asteroid-launcher/watchfaces/analog-weather-glow.qml
For rectangular watches the hands where not centered correctly. The issue was that the clocks width was used as height. This would look correct with a circular or square shaped screen.
> Fix hands center alignment analog-weather-glow

- numerals-duo-synth-neon-green/usr/share/asteroid-launcher/watchfaces/numerals-duo-synth-neon-green.qml
This smoothens the transition between the AoD mode (4 digit only) and normal mode (4 digits and date info) by adding a short animation.
Preview:
https://user-images.githubusercontent.com/7857908/218314603-66dbba41-1e6c-4ee2-9c90-1a988f6f8ef7.mp4
> numerals-duo-synth-neon-green: Add a transition animation between AoD and normal mode.

- watchface
This squashes a bug when using the text menu to test a watchface (wrong variable was used for the watchface name) and also uses the name of the function (one of `testface`, `deployface` or `cloneface`) rather than constructing it as in `"${action}"face` for added clarity and for ease of maintenance.
> Fix textmenu testcall

- watchface
This adds the update command to the watchface program and updates the version to 1.1.  When the user types "watchface update" it now runs "git pull" to update the project.  This was a suggestion from @dodoradio in response to an observation by @totalsonic1 in Matrix.
> Add update command to watchface

- watchface
This fixes #109 by using the --separate-output option to avoid introducing quotation marks in output lists and to give better compatibility with dialog.
> Fix whiptail multiple watch selection

- watchface
If the user tries to run the program with either a text or a gui menu but doesn't have a required program to run it, issue a clear error message instead of an unclear one.
> Add a warning if programs are missing

- watchface
This adds a few style improvements and also adds new non-interactive command "deployall" to deploy all watchfaces from the command line, and a similar "-e" or "--every" option to check all boxes by default when using the interactive version.
> Add all option

- loader.qml
- watchface
This adds an additional argument to loader.qml to specify the directory in which the watchface is loaded, and then modifies the watchface code to pass that argument.  The purpose is to allow for desktop testing of other kinds of qml files intended for watches.
> Allow passing an explicit directory for test

- analog-weather-glow/usr/share/asteroid-launcher/watchfaces/analog-weather-glow.qml
This resolves
https://github.com/AsteroidOS/unofficial-watchfaces/issues/124 by checking for 0K instead of trying to convert before checking.  Now days for which there is no weather data clearly show "No Weather Data" instead of showing -459F regardless of whether the user has chosen C or F for their preferred temperature units.
> [analog-weather-glow] Fix check for no weather data

- analog-silver-swerver/usr/share/asteroid-launcher/watchfaces/analog-silver-swerver.qml
Just as the title says, these two were included but no longer used.
> Remove unused MceBatteryState and MceCableState

- words-worte-palabras-mots-opensans/usr/share/asteroid-launcher/watchfaces/words-worte-palabras-mots-opensans.qml
Changed apostrophe ("'o clock" to "o' clock") in function generateTimEn minutesList to display the term "o' clock" in the conventional fashion -- "o' clock" is an abbreviation of the obsolete term "of the clock" so the apostrophe is placed where the term was shortened rather than before the "o".
> Update English minutesList in words-worte-palabras-mots-opensans.qml

- numerals-duo-neon-green/usr/share/asteroid-launcher/watchfaces/numerals-duo-neon-green.qml
This renames the DeviceInfo QML class in org.asteroid.utils to DeviceSpecs to avoid a conflict with an unrelated DeviceInfo class defined in org.nemomobile.systemsettings.
This fixes https://github.com/AsteroidOS/qml-asteroid/issues/56
> Rename DeviceInfo to DeviceSpecs to remove conflict
